version: '3'
services:
  # ==================== Discovery ====================
  discovery-service:
    build: ./discoveryserver
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - food-delivery-network

  # ======================Api gateway ========================
  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - food-delivery-network


  # ==================== MySQL Containers ====================
  mysql-restaurant:
    image: mysql:8.3.0
    container_name: mysql-restaurant
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: food_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_restaurant_data:/var/lib/mysql
      - ./docker/mysql/restaurant_init.sql:/docker-entrypoint-initdb.d/restaurant_init.sql
    networks:
      - food-delivery-network

  mysql-payment:
    image: mysql:8.3.0
    container_name: mysql-payment
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: payment_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_payment_data:/var/lib/mysql
      - ./docker/mysql/payment_init.sql:/docker-entrypoint-initdb.d/payment_init.sql
    networks:
      - food-delivery-network

  mysql-order:
    image: mysql:8.3.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: order_db
    ports:
      - "3309:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql
      - ./docker/mysql/order_init.sql:/docker-entrypoint-initdb.d/order_init.sql
    networks:
      - food-delivery-network

  mysql-delivery:
    image: mysql:8.3.0
    container_name: mysql-delivery
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: delivery_db
    ports:
      - "3401:3306"
    volumes:
      - mysql_delivery_data:/var/lib/mysql
      - ./docker/mysql/delivery_init.sql:/docker-entrypoint-initdb.d/delivery_init.sql
    networks:
      - food-delivery-network

  # ==================== Microservices ====================

  restaurant-service:
    build: ./Restaurant_Service
    container_name: restaurant-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-restaurant:3306/food_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - mysql-restaurant
      - discovery-service
    networks:
      - food-delivery-network


  payment-service:
    build: ./Payment_Service
    container_name: payment-service
    ports:
      - "8083:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-payment:3306/payment_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - mysql-payment
      - discovery-service
    networks:
      - food-delivery-network

  order-service:
    build: ./Order_Service
    container_name: order-service
    ports:
      - "8084:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order:3306/order_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - mysql-order
      - discovery-service
    networks:
      - food-delivery-network

  delivery-service:
    build: ./Delivery_Service
    container_name: delivery-service
    ports:
      - "8085:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-delivery:3306/delivery_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - mysql-delivery
      - discovery-service
    networks:
      - food-delivery-network

volumes:
  mysql_restaurant_data:
  mysql_payment_data:
  mysql_order_data:
  mysql_delivery_data:




networks:
  food-delivery-network:
    driver: bridge